### ISSUE TITLE
GalleryDataProcessor renders wrongly scaled pictures when using cropVariants

### ISSUE THREAD

**Issue by kabarakh** [TYPO3-Headless/headless#526]
We tried using a cropVariant to crop a picture to a 1:1 format. The FileDataProcessor grabs all the images, crops them (after adding cropVariant to processingConfiguration) and saves the pictures. Then the GalleryFileProcessor collects the images again, gets the original image and scales that to the size of the cropped image - but it won't crop the image, even when given the cropVariant as well.

For our project we decided to remove the GalleryDataProcessor from all content elements, but we still got the feeling that it's not behaving as it should ;)

**Comment by twoldanski** [comment]
Hi @kabarakh on which version of ext:headless you can reproduce this? on the latest? or some older version?

**Comment by kabarakh** [comment]
Hi @twoldanski 
we are using 3.2.2 via composer install

**Comment by ducrot** [comment]
I can confirm the issue. It exists since v3.2.0 and is still present in v.3.2.2. v3.1.2 works as expected in this point.

## Steps to Reproduce

1. Insert a first content element "Images Only" `image`
2. Insert a landscape format image.
3. Save
4. Insert a second content element "Images Only" `image`
5. Select a 1:1 cropping area
6. Save

### Expected behavior

Result with v3.1.2:

![headless-3 1](https://user-images.githubusercontent.com/3525119/218974227-641372f8-ec27-4256-86a7-8cc27fa55b33.png)

### Actual behavior

Result with > v3.2.x:

![headless-3 2](https://user-images.githubusercontent.com/3525119/218974428-4e9905e0-41ec-4e15-90a3-121e467b0384.png)
